// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manage.proto

/*
Package manage is a generated protocol buffer package.

It is generated from these files:
	manage.proto

It has these top-level messages:
	FiledConfig
	SetLogFieldConfigRequest
	SetLogFieldConfigResponse
	GetLogFieldConfigRequest
	GetLogFieldConfigResponse
	GetLogTransmitStatRequest
	GetLogTransmitStatResponse
	SetLogFilterConfigRequest
	SetLogFilterConfigResponse
	GetLogFilterConfigRequest
	GetLogFilterConfigResponse
*/
package manage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetLogFieldConfigResponse_Res_Status int32

const (
	SetLogFieldConfigResponse_SUCCEED SetLogFieldConfigResponse_Res_Status = 0
	SetLogFieldConfigResponse_FAILED  SetLogFieldConfigResponse_Res_Status = 1
)

var SetLogFieldConfigResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var SetLogFieldConfigResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x SetLogFieldConfigResponse_Res_Status) Enum() *SetLogFieldConfigResponse_Res_Status {
	p := new(SetLogFieldConfigResponse_Res_Status)
	*p = x
	return p
}
func (x SetLogFieldConfigResponse_Res_Status) String() string {
	return proto.EnumName(SetLogFieldConfigResponse_Res_Status_name, int32(x))
}
func (x *SetLogFieldConfigResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SetLogFieldConfigResponse_Res_Status_value, data, "SetLogFieldConfigResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = SetLogFieldConfigResponse_Res_Status(value)
	return nil
}
func (SetLogFieldConfigResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type GetLogFieldConfigResponse_Res_Status int32

const (
	GetLogFieldConfigResponse_SUCCEED GetLogFieldConfigResponse_Res_Status = 0
	GetLogFieldConfigResponse_FAILED  GetLogFieldConfigResponse_Res_Status = 1
)

var GetLogFieldConfigResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var GetLogFieldConfigResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x GetLogFieldConfigResponse_Res_Status) Enum() *GetLogFieldConfigResponse_Res_Status {
	p := new(GetLogFieldConfigResponse_Res_Status)
	*p = x
	return p
}
func (x GetLogFieldConfigResponse_Res_Status) String() string {
	return proto.EnumName(GetLogFieldConfigResponse_Res_Status_name, int32(x))
}
func (x *GetLogFieldConfigResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetLogFieldConfigResponse_Res_Status_value, data, "GetLogFieldConfigResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = GetLogFieldConfigResponse_Res_Status(value)
	return nil
}
func (GetLogFieldConfigResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type GetLogTransmitStatResponse_Res_Status int32

const (
	GetLogTransmitStatResponse_SUCCEED GetLogTransmitStatResponse_Res_Status = 0
	GetLogTransmitStatResponse_FAILED  GetLogTransmitStatResponse_Res_Status = 1
)

var GetLogTransmitStatResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var GetLogTransmitStatResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x GetLogTransmitStatResponse_Res_Status) Enum() *GetLogTransmitStatResponse_Res_Status {
	p := new(GetLogTransmitStatResponse_Res_Status)
	*p = x
	return p
}
func (x GetLogTransmitStatResponse_Res_Status) String() string {
	return proto.EnumName(GetLogTransmitStatResponse_Res_Status_name, int32(x))
}
func (x *GetLogTransmitStatResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetLogTransmitStatResponse_Res_Status_value, data, "GetLogTransmitStatResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = GetLogTransmitStatResponse_Res_Status(value)
	return nil
}
func (GetLogTransmitStatResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type SetLogFilterConfigResponse_Res_Status int32

const (
	SetLogFilterConfigResponse_SUCCEED SetLogFilterConfigResponse_Res_Status = 0
	SetLogFilterConfigResponse_FAILED  SetLogFilterConfigResponse_Res_Status = 1
)

var SetLogFilterConfigResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var SetLogFilterConfigResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x SetLogFilterConfigResponse_Res_Status) Enum() *SetLogFilterConfigResponse_Res_Status {
	p := new(SetLogFilterConfigResponse_Res_Status)
	*p = x
	return p
}
func (x SetLogFilterConfigResponse_Res_Status) String() string {
	return proto.EnumName(SetLogFilterConfigResponse_Res_Status_name, int32(x))
}
func (x *SetLogFilterConfigResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SetLogFilterConfigResponse_Res_Status_value, data, "SetLogFilterConfigResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = SetLogFilterConfigResponse_Res_Status(value)
	return nil
}
func (SetLogFilterConfigResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

type GetLogFilterConfigResponse_Res_Status int32

const (
	GetLogFilterConfigResponse_SUCCEED GetLogFilterConfigResponse_Res_Status = 0
	GetLogFilterConfigResponse_FAILED  GetLogFilterConfigResponse_Res_Status = 1
)

var GetLogFilterConfigResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var GetLogFilterConfigResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x GetLogFilterConfigResponse_Res_Status) Enum() *GetLogFilterConfigResponse_Res_Status {
	p := new(GetLogFilterConfigResponse_Res_Status)
	*p = x
	return p
}
func (x GetLogFilterConfigResponse_Res_Status) String() string {
	return proto.EnumName(GetLogFilterConfigResponse_Res_Status_name, int32(x))
}
func (x *GetLogFilterConfigResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetLogFilterConfigResponse_Res_Status_value, data, "GetLogFilterConfigResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = GetLogFilterConfigResponse_Res_Status(value)
	return nil
}
func (GetLogFilterConfigResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

type FiledConfig struct {
	Field            *string `protobuf:"bytes,1,req,name=field" json:"field,omitempty"`
	Regex            *string `protobuf:"bytes,2,req,name=regex" json:"regex,omitempty"`
	Istrans          *bool   `protobuf:"varint,3,req,name=istrans" json:"istrans,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FiledConfig) Reset()                    { *m = FiledConfig{} }
func (m *FiledConfig) String() string            { return proto.CompactTextString(m) }
func (*FiledConfig) ProtoMessage()               {}
func (*FiledConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FiledConfig) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *FiledConfig) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *FiledConfig) GetIstrans() bool {
	if m != nil && m.Istrans != nil {
		return *m.Istrans
	}
	return false
}

type SetLogFieldConfigRequest struct {
	Application      *string      `protobuf:"bytes,1,req,name=application" json:"application,omitempty"`
	Op               *bool        `protobuf:"varint,2,req,name=op" json:"op,omitempty"`
	Fieldconfigs     *FiledConfig `protobuf:"bytes,3,opt,name=fieldconfigs" json:"fieldconfigs,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SetLogFieldConfigRequest) Reset()                    { *m = SetLogFieldConfigRequest{} }
func (m *SetLogFieldConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetLogFieldConfigRequest) ProtoMessage()               {}
func (*SetLogFieldConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SetLogFieldConfigRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *SetLogFieldConfigRequest) GetOp() bool {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return false
}

func (m *SetLogFieldConfigRequest) GetFieldconfigs() *FiledConfig {
	if m != nil {
		return m.Fieldconfigs
	}
	return nil
}

type SetLogFieldConfigResponse struct {
	Status           *SetLogFieldConfigResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.SetLogFieldConfigResponse_Res_Status" json:"status,omitempty"`
	Error            *string                               `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *SetLogFieldConfigResponse) Reset()                    { *m = SetLogFieldConfigResponse{} }
func (m *SetLogFieldConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetLogFieldConfigResponse) ProtoMessage()               {}
func (*SetLogFieldConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetLogFieldConfigResponse) GetStatus() SetLogFieldConfigResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return SetLogFieldConfigResponse_SUCCEED
}

func (m *SetLogFieldConfigResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GetLogFieldConfigRequest struct {
	Application      *string `protobuf:"bytes,1,req,name=application" json:"application,omitempty"`
	Field            *string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLogFieldConfigRequest) Reset()                    { *m = GetLogFieldConfigRequest{} }
func (m *GetLogFieldConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogFieldConfigRequest) ProtoMessage()               {}
func (*GetLogFieldConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetLogFieldConfigRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *GetLogFieldConfigRequest) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

type GetLogFieldConfigResponse struct {
	Status           *GetLogFieldConfigResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.GetLogFieldConfigResponse_Res_Status" json:"status,omitempty"`
	Error            *string                               `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Fieldconfigs     []*FiledConfig                        `protobuf:"bytes,3,rep,name=fieldconfigs" json:"fieldconfigs,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *GetLogFieldConfigResponse) Reset()                    { *m = GetLogFieldConfigResponse{} }
func (m *GetLogFieldConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogFieldConfigResponse) ProtoMessage()               {}
func (*GetLogFieldConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetLogFieldConfigResponse) GetStatus() GetLogFieldConfigResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GetLogFieldConfigResponse_SUCCEED
}

func (m *GetLogFieldConfigResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetLogFieldConfigResponse) GetFieldconfigs() []*FiledConfig {
	if m != nil {
		return m.Fieldconfigs
	}
	return nil
}

type GetLogTransmitStatRequest struct {
	Application      *string `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Logtype          *bool   `protobuf:"varint,2,opt,name=logtype" json:"logtype,omitempty"`
	Startime         *int64  `protobuf:"varint,3,req,name=startime" json:"startime,omitempty"`
	Endtime          *int64  `protobuf:"varint,4,req,name=endtime" json:"endtime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLogTransmitStatRequest) Reset()                    { *m = GetLogTransmitStatRequest{} }
func (m *GetLogTransmitStatRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogTransmitStatRequest) ProtoMessage()               {}
func (*GetLogTransmitStatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetLogTransmitStatRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *GetLogTransmitStatRequest) GetLogtype() bool {
	if m != nil && m.Logtype != nil {
		return *m.Logtype
	}
	return false
}

func (m *GetLogTransmitStatRequest) GetStartime() int64 {
	if m != nil && m.Startime != nil {
		return *m.Startime
	}
	return 0
}

func (m *GetLogTransmitStatRequest) GetEndtime() int64 {
	if m != nil && m.Endtime != nil {
		return *m.Endtime
	}
	return 0
}

type GetLogTransmitStatResponse struct {
	Status           *GetLogTransmitStatResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.GetLogTransmitStatResponse_Res_Status" json:"status,omitempty"`
	Error            *string                                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Num              *int32                                 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *GetLogTransmitStatResponse) Reset()                    { *m = GetLogTransmitStatResponse{} }
func (m *GetLogTransmitStatResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogTransmitStatResponse) ProtoMessage()               {}
func (*GetLogTransmitStatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetLogTransmitStatResponse) GetStatus() GetLogTransmitStatResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GetLogTransmitStatResponse_SUCCEED
}

func (m *GetLogTransmitStatResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetLogTransmitStatResponse) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type SetLogFilterConfigRequest struct {
	Op               *bool   `protobuf:"varint,1,req,name=op" json:"op,omitempty"`
	Srcid            *string `protobuf:"bytes,2,req,name=srcid" json:"srcid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetLogFilterConfigRequest) Reset()                    { *m = SetLogFilterConfigRequest{} }
func (m *SetLogFilterConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetLogFilterConfigRequest) ProtoMessage()               {}
func (*SetLogFilterConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetLogFilterConfigRequest) GetOp() bool {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return false
}

func (m *SetLogFilterConfigRequest) GetSrcid() string {
	if m != nil && m.Srcid != nil {
		return *m.Srcid
	}
	return ""
}

type SetLogFilterConfigResponse struct {
	Status           *SetLogFilterConfigResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.SetLogFilterConfigResponse_Res_Status" json:"status,omitempty"`
	Error            *string                                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *SetLogFilterConfigResponse) Reset()                    { *m = SetLogFilterConfigResponse{} }
func (m *SetLogFilterConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetLogFilterConfigResponse) ProtoMessage()               {}
func (*SetLogFilterConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SetLogFilterConfigResponse) GetStatus() SetLogFilterConfigResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return SetLogFilterConfigResponse_SUCCEED
}

func (m *SetLogFilterConfigResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GetLogFilterConfigRequest struct {
	Application      *bool  `protobuf:"varint,1,opt,name=application" json:"application,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetLogFilterConfigRequest) Reset()                    { *m = GetLogFilterConfigRequest{} }
func (m *GetLogFilterConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogFilterConfigRequest) ProtoMessage()               {}
func (*GetLogFilterConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetLogFilterConfigRequest) GetApplication() bool {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return false
}

type GetLogFilterConfigResponse struct {
	Status           *GetLogFilterConfigResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.GetLogFilterConfigResponse_Res_Status" json:"status,omitempty"`
	Error            *string                                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Srcids           []string                               `protobuf:"bytes,3,rep,name=srcids" json:"srcids,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *GetLogFilterConfigResponse) Reset()                    { *m = GetLogFilterConfigResponse{} }
func (m *GetLogFilterConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogFilterConfigResponse) ProtoMessage()               {}
func (*GetLogFilterConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetLogFilterConfigResponse) GetStatus() GetLogFilterConfigResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GetLogFilterConfigResponse_SUCCEED
}

func (m *GetLogFilterConfigResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetLogFilterConfigResponse) GetSrcids() []string {
	if m != nil {
		return m.Srcids
	}
	return nil
}

func init() {
	proto.RegisterType((*FiledConfig)(nil), "manage.FiledConfig")
	proto.RegisterType((*SetLogFieldConfigRequest)(nil), "manage.SetLogFieldConfigRequest")
	proto.RegisterType((*SetLogFieldConfigResponse)(nil), "manage.SetLogFieldConfigResponse")
	proto.RegisterType((*GetLogFieldConfigRequest)(nil), "manage.GetLogFieldConfigRequest")
	proto.RegisterType((*GetLogFieldConfigResponse)(nil), "manage.GetLogFieldConfigResponse")
	proto.RegisterType((*GetLogTransmitStatRequest)(nil), "manage.GetLogTransmitStatRequest")
	proto.RegisterType((*GetLogTransmitStatResponse)(nil), "manage.GetLogTransmitStatResponse")
	proto.RegisterType((*SetLogFilterConfigRequest)(nil), "manage.SetLogFilterConfigRequest")
	proto.RegisterType((*SetLogFilterConfigResponse)(nil), "manage.SetLogFilterConfigResponse")
	proto.RegisterType((*GetLogFilterConfigRequest)(nil), "manage.GetLogFilterConfigRequest")
	proto.RegisterType((*GetLogFilterConfigResponse)(nil), "manage.GetLogFilterConfigResponse")
	proto.RegisterEnum("manage.SetLogFieldConfigResponse_Res_Status", SetLogFieldConfigResponse_Res_Status_name, SetLogFieldConfigResponse_Res_Status_value)
	proto.RegisterEnum("manage.GetLogFieldConfigResponse_Res_Status", GetLogFieldConfigResponse_Res_Status_name, GetLogFieldConfigResponse_Res_Status_value)
	proto.RegisterEnum("manage.GetLogTransmitStatResponse_Res_Status", GetLogTransmitStatResponse_Res_Status_name, GetLogTransmitStatResponse_Res_Status_value)
	proto.RegisterEnum("manage.SetLogFilterConfigResponse_Res_Status", SetLogFilterConfigResponse_Res_Status_name, SetLogFilterConfigResponse_Res_Status_value)
	proto.RegisterEnum("manage.GetLogFilterConfigResponse_Res_Status", GetLogFilterConfigResponse_Res_Status_name, GetLogFilterConfigResponse_Res_Status_value)
}

func init() { proto.RegisterFile("manage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x0d, 0xeb, 0xb2, 0x93, 0x6d, 0x0c, 0xef, 0x26, 0xec, 0x6a, 0xb3, 0x84, 0x54, 0x24,
	0xa8, 0x50, 0x2f, 0xb8, 0x1a, 0x48, 0x50, 0xd6, 0x08, 0x69, 0xdc, 0x50, 0x90, 0x90, 0xb8, 0x40,
	0x51, 0x73, 0x1a, 0x59, 0x4a, 0xe3, 0xe0, 0xb8, 0x08, 0xee, 0x78, 0x03, 0xc4, 0x0b, 0x20, 0xf1,
	0x1a, 0x3c, 0x0a, 0x4f, 0x83, 0xed, 0x74, 0x5d, 0xd7, 0xe6, 0xa7, 0x81, 0x3b, 0xdb, 0xc9, 0xf7,
	0x9d, 0xf3, 0x7d, 0xfe, 0x7c, 0x60, 0x7f, 0x16, 0xa6, 0x61, 0x8c, 0xfd, 0x4c, 0x0a, 0x25, 0x68,
	0xb7, 0xd8, 0xb1, 0x73, 0xf0, 0x46, 0x3c, 0xc1, 0x68, 0x28, 0xd2, 0x29, 0x8f, 0xe9, 0x01, 0xec,
	0x4c, 0x39, 0x26, 0x91, 0x4f, 0x4e, 0x3b, 0xbd, 0x3d, 0xb3, 0x95, 0x18, 0xe3, 0x17, 0xbf, 0x63,
	0xb7, 0x77, 0x60, 0x97, 0xe7, 0x4a, 0x86, 0x69, 0xee, 0x3b, 0xfa, 0xc0, 0x65, 0x53, 0xf0, 0xc7,
	0xa8, 0x2e, 0x45, 0x3c, 0x32, 0xa0, 0x82, 0xe3, 0x0d, 0x7e, 0x9a, 0x63, 0xae, 0xe8, 0x31, 0x78,
	0x61, 0x96, 0x25, 0x7c, 0x12, 0x2a, 0x2e, 0xd2, 0x05, 0x21, 0x40, 0x47, 0x64, 0x96, 0xcd, 0xa5,
	0x0f, 0x60, 0xdf, 0xd6, 0x9a, 0x58, 0x98, 0xa1, 0x24, 0x3d, 0x6f, 0x70, 0xdc, 0x5f, 0xf4, 0xb9,
	0xd2, 0x16, 0xfb, 0x4e, 0xe0, 0x5e, 0x49, 0xa1, 0x3c, 0x13, 0x69, 0x8e, 0xf4, 0x1c, 0xba, 0xb9,
	0x0a, 0xd5, 0x3c, 0xb7, 0x45, 0x0e, 0x07, 0x0f, 0xaf, 0x28, 0x2a, 0x21, 0x7d, 0xbd, 0xf8, 0x38,
	0xb6, 0x18, 0xa3, 0x11, 0xa5, 0x14, 0x52, 0x77, 0x45, 0x7a, 0x7b, 0xec, 0x3e, 0xc0, 0xca, 0x47,
	0x0f, 0x76, 0xc7, 0xef, 0x86, 0xc3, 0x8b, 0x8b, 0x97, 0x47, 0xb7, 0x74, 0xf3, 0xdd, 0xd1, 0xf3,
	0x57, 0x97, 0x7a, 0x4d, 0xd8, 0x33, 0xf0, 0x83, 0x56, 0xca, 0x97, 0xce, 0x16, 0x65, 0x7e, 0x6b,
	0x45, 0x41, 0x7b, 0x45, 0x41, 0x7b, 0x45, 0x25, 0x3e, 0x3b, 0x55, 0x3e, 0x6f, 0x29, 0x3e, 0xba,
	0xea, 0xfd, 0xad, 0xc9, 0xc2, 0x8c, 0x2b, 0x03, 0xa8, 0x54, 0x4f, 0x8a, 0xe4, 0x24, 0x22, 0x56,
	0x5f, 0x33, 0xb4, 0x4d, 0xb9, 0xf4, 0x08, 0x5c, 0xad, 0x50, 0x2a, 0x3e, 0x43, 0x9b, 0x25, 0xc7,
	0xfc, 0x82, 0x69, 0x64, 0x0f, 0x6e, 0x9b, 0x03, 0xf6, 0x93, 0xc0, 0x49, 0x59, 0x99, 0x85, 0x47,
	0x4f, 0xd7, 0x3c, 0x7a, 0x74, 0xd3, 0xa3, 0x32, 0x4c, 0x8d, 0x49, 0x1e, 0x38, 0xe9, 0x7c, 0x66,
	0x5b, 0xd9, 0xd9, 0xd6, 0x86, 0x27, 0xd7, 0xa1, 0x4c, 0x14, 0xca, 0x9b, 0x21, 0x28, 0x92, 0x4e,
	0x6c, 0xd2, 0x75, 0xad, 0x5c, 0x4e, 0x78, 0x54, 0x3c, 0x23, 0xf6, 0x43, 0x0b, 0x2b, 0x03, 0x36,
	0x09, 0xab, 0xc6, 0xfc, 0x7f, 0x9e, 0x1f, 0x5f, 0xc7, 0x71, 0x53, 0x4b, 0xc9, 0x95, 0xba, 0xec,
	0xd7, 0xf2, 0x7a, 0xda, 0xa9, 0x08, 0xfe, 0x41, 0x05, 0x3d, 0xd4, 0x6c, 0xc6, 0xc1, 0x22, 0xbd,
	0xdb, 0xaa, 0x1a, 0xfc, 0x71, 0xe0, 0xe0, 0xb5, 0x2d, 0x3b, 0x46, 0xf9, 0x99, 0x4f, 0x90, 0x7e,
	0x00, 0xba, 0x69, 0x23, 0x3d, 0xab, 0xb3, 0xd8, 0x7a, 0x70, 0xc2, 0x9a, 0x6f, 0xc1, 0x90, 0x07,
	0x35, 0xe4, 0x41, 0x33, 0x79, 0x8d, 0xa1, 0xef, 0xe1, 0xee, 0xc6, 0x3c, 0xa3, 0xa7, 0x35, 0xa3,
	0xae, 0xa0, 0x3e, 0x6b, 0x1c, 0x86, 0x86, 0x39, 0xa8, 0x66, 0x0e, 0x1a, 0x99, 0xab, 0xe7, 0xd8,
	0xd2, 0x90, 0xd5, 0xd7, 0xb8, 0x6e, 0x48, 0xc9, 0x10, 0x59, 0x37, 0xa4, 0xec, 0x31, 0xbf, 0x70,
	0xbe, 0x11, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x56, 0x1d, 0x3a, 0xa7, 0xd6, 0x06, 0x00, 0x00,
}
