// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manage.proto

/*
Package manage is a generated protocol buffer package.

It is generated from these files:
	manage.proto

It has these top-level messages:
	FiledConfig
	SetLogFieldConfigRequest
	SetLogFieldConfigResponse
	GetLogFieldConfigRequest
	GetLogFieldConfigResponse
	GetLogTransmitStatRequest
	GetLogTransmitStatResponse
*/
package manage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetLogFieldConfigResponse_Res_Status int32

const (
	SetLogFieldConfigResponse_SUCCEED SetLogFieldConfigResponse_Res_Status = 0
	SetLogFieldConfigResponse_FAILED  SetLogFieldConfigResponse_Res_Status = 1
)

var SetLogFieldConfigResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var SetLogFieldConfigResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x SetLogFieldConfigResponse_Res_Status) Enum() *SetLogFieldConfigResponse_Res_Status {
	p := new(SetLogFieldConfigResponse_Res_Status)
	*p = x
	return p
}
func (x SetLogFieldConfigResponse_Res_Status) String() string {
	return proto.EnumName(SetLogFieldConfigResponse_Res_Status_name, int32(x))
}
func (x *SetLogFieldConfigResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SetLogFieldConfigResponse_Res_Status_value, data, "SetLogFieldConfigResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = SetLogFieldConfigResponse_Res_Status(value)
	return nil
}
func (SetLogFieldConfigResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type GetLogFieldConfigResponse_Res_Status int32

const (
	GetLogFieldConfigResponse_SUCCEED GetLogFieldConfigResponse_Res_Status = 0
	GetLogFieldConfigResponse_FAILED  GetLogFieldConfigResponse_Res_Status = 1
)

var GetLogFieldConfigResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var GetLogFieldConfigResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x GetLogFieldConfigResponse_Res_Status) Enum() *GetLogFieldConfigResponse_Res_Status {
	p := new(GetLogFieldConfigResponse_Res_Status)
	*p = x
	return p
}
func (x GetLogFieldConfigResponse_Res_Status) String() string {
	return proto.EnumName(GetLogFieldConfigResponse_Res_Status_name, int32(x))
}
func (x *GetLogFieldConfigResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetLogFieldConfigResponse_Res_Status_value, data, "GetLogFieldConfigResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = GetLogFieldConfigResponse_Res_Status(value)
	return nil
}
func (GetLogFieldConfigResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type GetLogTransmitStatResponse_Res_Status int32

const (
	GetLogTransmitStatResponse_SUCCEED GetLogTransmitStatResponse_Res_Status = 0
	GetLogTransmitStatResponse_FAILED  GetLogTransmitStatResponse_Res_Status = 1
)

var GetLogTransmitStatResponse_Res_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}
var GetLogTransmitStatResponse_Res_Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x GetLogTransmitStatResponse_Res_Status) Enum() *GetLogTransmitStatResponse_Res_Status {
	p := new(GetLogTransmitStatResponse_Res_Status)
	*p = x
	return p
}
func (x GetLogTransmitStatResponse_Res_Status) String() string {
	return proto.EnumName(GetLogTransmitStatResponse_Res_Status_name, int32(x))
}
func (x *GetLogTransmitStatResponse_Res_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetLogTransmitStatResponse_Res_Status_value, data, "GetLogTransmitStatResponse_Res_Status")
	if err != nil {
		return err
	}
	*x = GetLogTransmitStatResponse_Res_Status(value)
	return nil
}
func (GetLogTransmitStatResponse_Res_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type FiledConfig struct {
	Field            *string `protobuf:"bytes,1,req,name=field" json:"field,omitempty"`
	Regex            *string `protobuf:"bytes,2,req,name=regex" json:"regex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FiledConfig) Reset()                    { *m = FiledConfig{} }
func (m *FiledConfig) String() string            { return proto.CompactTextString(m) }
func (*FiledConfig) ProtoMessage()               {}
func (*FiledConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FiledConfig) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *FiledConfig) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

type SetLogFieldConfigRequest struct {
	Application      *string        `protobuf:"bytes,1,req,name=application" json:"application,omitempty"`
	Fieldconfigs     []*FiledConfig `protobuf:"bytes,2,rep,name=fieldconfigs" json:"fieldconfigs,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SetLogFieldConfigRequest) Reset()                    { *m = SetLogFieldConfigRequest{} }
func (m *SetLogFieldConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*SetLogFieldConfigRequest) ProtoMessage()               {}
func (*SetLogFieldConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SetLogFieldConfigRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *SetLogFieldConfigRequest) GetFieldconfigs() []*FiledConfig {
	if m != nil {
		return m.Fieldconfigs
	}
	return nil
}

type SetLogFieldConfigResponse struct {
	Status           *SetLogFieldConfigResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.SetLogFieldConfigResponse_Res_Status" json:"status,omitempty"`
	Error            *string                               `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *SetLogFieldConfigResponse) Reset()                    { *m = SetLogFieldConfigResponse{} }
func (m *SetLogFieldConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*SetLogFieldConfigResponse) ProtoMessage()               {}
func (*SetLogFieldConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetLogFieldConfigResponse) GetStatus() SetLogFieldConfigResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return SetLogFieldConfigResponse_SUCCEED
}

func (m *SetLogFieldConfigResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GetLogFieldConfigRequest struct {
	Application      *string `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Field            *string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLogFieldConfigRequest) Reset()                    { *m = GetLogFieldConfigRequest{} }
func (m *GetLogFieldConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogFieldConfigRequest) ProtoMessage()               {}
func (*GetLogFieldConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetLogFieldConfigRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *GetLogFieldConfigRequest) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

type GetLogFieldConfigResponse struct {
	Status           *GetLogFieldConfigResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.GetLogFieldConfigResponse_Res_Status" json:"status,omitempty"`
	Error            *string                               `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Fieldconfigs     []*FiledConfig                        `protobuf:"bytes,3,rep,name=fieldconfigs" json:"fieldconfigs,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *GetLogFieldConfigResponse) Reset()                    { *m = GetLogFieldConfigResponse{} }
func (m *GetLogFieldConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogFieldConfigResponse) ProtoMessage()               {}
func (*GetLogFieldConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetLogFieldConfigResponse) GetStatus() GetLogFieldConfigResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GetLogFieldConfigResponse_SUCCEED
}

func (m *GetLogFieldConfigResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetLogFieldConfigResponse) GetFieldconfigs() []*FiledConfig {
	if m != nil {
		return m.Fieldconfigs
	}
	return nil
}

type GetLogTransmitStatRequest struct {
	Application      *string `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Logtype          *bool   `protobuf:"varint,2,opt,name=logtype" json:"logtype,omitempty"`
	Startime         *int64  `protobuf:"varint,3,req,name=startime" json:"startime,omitempty"`
	Endtime          *int64  `protobuf:"varint,4,req,name=endtime" json:"endtime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLogTransmitStatRequest) Reset()                    { *m = GetLogTransmitStatRequest{} }
func (m *GetLogTransmitStatRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLogTransmitStatRequest) ProtoMessage()               {}
func (*GetLogTransmitStatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetLogTransmitStatRequest) GetApplication() string {
	if m != nil && m.Application != nil {
		return *m.Application
	}
	return ""
}

func (m *GetLogTransmitStatRequest) GetLogtype() bool {
	if m != nil && m.Logtype != nil {
		return *m.Logtype
	}
	return false
}

func (m *GetLogTransmitStatRequest) GetStartime() int64 {
	if m != nil && m.Startime != nil {
		return *m.Startime
	}
	return 0
}

func (m *GetLogTransmitStatRequest) GetEndtime() int64 {
	if m != nil && m.Endtime != nil {
		return *m.Endtime
	}
	return 0
}

type GetLogTransmitStatResponse struct {
	Status           *GetLogTransmitStatResponse_Res_Status `protobuf:"varint,1,req,name=status,enum=manage.GetLogTransmitStatResponse_Res_Status" json:"status,omitempty"`
	Error            *string                                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Num              *int64                                 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *GetLogTransmitStatResponse) Reset()                    { *m = GetLogTransmitStatResponse{} }
func (m *GetLogTransmitStatResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLogTransmitStatResponse) ProtoMessage()               {}
func (*GetLogTransmitStatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetLogTransmitStatResponse) GetStatus() GetLogTransmitStatResponse_Res_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return GetLogTransmitStatResponse_SUCCEED
}

func (m *GetLogTransmitStatResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *GetLogTransmitStatResponse) GetNum() int64 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*FiledConfig)(nil), "manage.FiledConfig")
	proto.RegisterType((*SetLogFieldConfigRequest)(nil), "manage.SetLogFieldConfigRequest")
	proto.RegisterType((*SetLogFieldConfigResponse)(nil), "manage.SetLogFieldConfigResponse")
	proto.RegisterType((*GetLogFieldConfigRequest)(nil), "manage.GetLogFieldConfigRequest")
	proto.RegisterType((*GetLogFieldConfigResponse)(nil), "manage.GetLogFieldConfigResponse")
	proto.RegisterType((*GetLogTransmitStatRequest)(nil), "manage.GetLogTransmitStatRequest")
	proto.RegisterType((*GetLogTransmitStatResponse)(nil), "manage.GetLogTransmitStatResponse")
	proto.RegisterEnum("manage.SetLogFieldConfigResponse_Res_Status", SetLogFieldConfigResponse_Res_Status_name, SetLogFieldConfigResponse_Res_Status_value)
	proto.RegisterEnum("manage.GetLogFieldConfigResponse_Res_Status", GetLogFieldConfigResponse_Res_Status_name, GetLogFieldConfigResponse_Res_Status_value)
	proto.RegisterEnum("manage.GetLogTransmitStatResponse_Res_Status", GetLogTransmitStatResponse_Res_Status_name, GetLogTransmitStatResponse_Res_Status_value)
}

func init() { proto.RegisterFile("manage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0xbb, 0x76, 0x0b, 0x74, 0x0c, 0x2d, 0x5d, 0x2e, 0x2e, 0x27, 0xb0, 0x54, 0x89, 0xaa,
	0x2d, 0x07, 0xce, 0x6d, 0xa5, 0x84, 0x80, 0x15, 0x89, 0x5c, 0xe2, 0x44, 0x8a, 0x92, 0x43, 0x64,
	0xe1, 0xc5, 0x5a, 0xc9, 0xf6, 0x3a, 0xeb, 0x25, 0x4a, 0x6e, 0x79, 0x83, 0xbc, 0x41, 0x94, 0xe7,
	0xc8, 0xd3, 0x65, 0x77, 0x0d, 0x12, 0x09, 0xd8, 0xc0, 0xcd, 0xb3, 0x9e, 0xff, 0x9f, 0xf9, 0x3f,
	0x0d, 0xd4, 0x63, 0x3f, 0xf1, 0x43, 0xd2, 0x4f, 0x39, 0x13, 0x0c, 0x57, 0xf2, 0xca, 0xf9, 0x05,
	0xd6, 0x98, 0x46, 0x24, 0x18, 0xb2, 0x64, 0x46, 0x43, 0xdc, 0x80, 0x4f, 0x33, 0x4a, 0xa2, 0xc0,
	0x46, 0x1d, 0xa3, 0xf7, 0x59, 0x95, 0x9c, 0x84, 0xe4, 0xce, 0x36, 0x54, 0xe9, 0x5c, 0x82, 0xed,
	0x11, 0x31, 0x61, 0xe1, 0x58, 0xf5, 0xe4, 0x92, 0x53, 0x72, 0x33, 0x27, 0x99, 0xc0, 0x2d, 0xb0,
	0xfc, 0x34, 0x8d, 0xe8, 0xd4, 0x17, 0x94, 0x25, 0x0b, 0xfd, 0x4f, 0xa8, 0x6b, 0xbb, 0xa9, 0x6e,
	0xcd, 0xa4, 0x8d, 0xd9, 0xb3, 0x06, 0xad, 0xfe, 0x62, 0x95, 0x95, 0xc9, 0xce, 0x23, 0x82, 0xef,
	0x1b, 0xcc, 0xb3, 0x94, 0x25, 0x19, 0xc1, 0x7f, 0xa1, 0x92, 0x09, 0x5f, 0xcc, 0x33, 0x6d, 0xfc,
	0x65, 0xf0, 0x7b, 0x69, 0x51, 0x28, 0xe9, 0xcb, 0x8f, 0x6b, 0x4f, 0x6b, 0x54, 0x0c, 0xc2, 0x39,
	0xe3, 0x72, 0x3e, 0x92, 0x31, 0x7e, 0x00, 0xac, 0xfc, 0xb4, 0xa0, 0xea, 0x9d, 0x0f, 0x87, 0xa3,
	0xd1, 0x51, 0xf3, 0x03, 0x06, 0xa8, 0x8c, 0x0f, 0x8e, 0x27, 0xf2, 0x1b, 0x39, 0xff, 0xc1, 0x76,
	0x77, 0x4e, 0x8b, 0x72, 0x5a, 0x39, 0xbc, 0x7c, 0xcc, 0x8b, 0x4c, 0xe4, 0xee, 0x9f, 0xc8, 0xdd,
	0x3f, 0xd1, 0x1a, 0x67, 0xb3, 0x98, 0xf3, 0x8e, 0xe1, 0x83, 0xe5, 0xee, 0x67, 0xdc, 0x4f, 0xb2,
	0x98, 0x0a, 0x25, 0x28, 0x4d, 0xff, 0x15, 0xaa, 0x11, 0x0b, 0xc5, 0x7d, 0x4a, 0xf4, 0x52, 0x35,
	0xdc, 0x84, 0x9a, 0x4c, 0xc8, 0x05, 0x8d, 0x89, 0x5c, 0xc8, 0xe8, 0x99, 0xaa, 0x85, 0x24, 0x81,
	0x7e, 0xf8, 0xa8, 0x1e, 0x9c, 0x27, 0x04, 0xed, 0x4d, 0x63, 0x16, 0x8c, 0xfe, 0xbd, 0x63, 0xf4,
	0xe7, 0x2d, 0xa3, 0x4d, 0x9a, 0x12, 0x48, 0x16, 0x98, 0xc9, 0x3c, 0xce, 0x57, 0xd9, 0x11, 0xc3,
	0xe0, 0xd9, 0x80, 0xc6, 0x89, 0x9e, 0xe9, 0x11, 0x7e, 0x4b, 0xa7, 0x04, 0x5f, 0xc0, 0xb7, 0xb5,
	0x9b, 0xc3, 0x9d, 0x92, 0x73, 0xd4, 0xc8, 0xda, 0xdd, 0xad, 0x07, 0xab, 0x9c, 0xdd, 0x62, 0x67,
	0x77, 0xab, 0x73, 0xf1, 0xad, 0x5d, 0x01, 0x5e, 0x27, 0x86, 0xbb, 0x65, 0x34, 0x73, 0x6f, 0x67,
	0x3b, 0xf0, 0x43, 0xf3, 0x01, 0xa1, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x0a, 0x59, 0xdb,
	0x5d, 0x04, 0x00, 0x00,
}
